on:
  push:
    branches: [ "main" ]

jobs:
  ios-build:
    name: iOS main Build
    runs-on: macos-latest

    steps:
      - name: Show runner info
        run: uname -a

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Node dependencies
        run: yarn install

      - name: Install Bundler
        run: |
          sudo gem install bundler

      - name: Install Ruby dependencies
        working-directory: ios
        run: |
          bundle install

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        working-directory: ios
        run: |
          bundle exec pod install --repo-update

      - name: Build iOS JS Bundle
        run: yarn run package-ios

      - name: Run Fastlane (TestFlight Build)
        working-directory: ios
        run: |
          bundle exec fastlane build_testflight

  android-build:
    name: Android main Build
    runs-on: self-hosted

    steps:
      - name: Show runner info
        run: uname -a

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Node dependencies
        run: yarn install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Android project
        working-directory: android
        run: ./gradlew build

      - name: Build Android JS Bundle
        run: yarn run package-android

      - name: Delete Android build duplicate assets
        run: yarn run delete-pics

      - name: Install Bundler
        working-directory: android
        run: |
          gem install bundler

      - name: Install Ruby dependencies
        working-directory: android
        run: |
          bundle install

      - name: Run Fastlane (QA Build)
        working-directory: android
        run: |
          bundle exec fastlane build_qa
